staging:
  aws_access_key: AKIAIROTVAKBJZWJDRFA
  aws_secret_access_key: Im4saOEELcfwO2Cjqjp99FybgyILtD6n4kWYplGU
  bucket_base_name: yourbucket

production:
  aws_access_key: AKIAIROTVAKBJZWJDRFA
  aws_secret_access_key: Im4saOEELcfwO2Cjqjp99FybgyILtD6n4kWYplGU
  bucket_base_name: playlist

development:
  aws_access_key: AKIAIROTVAKBJZWJDRFA
  aws_secret_access_key: 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
  bucket_base_name: playlist