staging:
  aws_access_key: hidden
  aws_secret_access_key: hidden
  bucket_base_name: yourbucket

production:
  aws_access_key: hidden
  aws_secret_access_key: hidden
  bucket_base_name: playlist

development:
  aws_access_key: hidden
  aws_secret_access_key: hidden
  bucket_base_name: playlist
